# Generated by Django 5.2.4 on 2025-09-10 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0009_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='Card', max_length=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.enrollments')),
            ],
        ),
    ]
