# Generated by Django 5.2.4 on 2025-09-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='payment_date',
            new_name='created_at',
        ),
    ]
