# Generated by Django 5.2.4 on 2025-09-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_payment_date_payments_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='transaction_id',
            new_name='stripe_charge_id',
        ),
    ]
