# Generated by Django 5.2.4 on 2025-09-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_transaction_id_payments_stripe_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='Cash', max_length=10),
        ),
    ]
