# Generated by Django 5.2.4 on 2025-09-02 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(choices=[('months', 'Months'), ('weeks', 'Weeks')], default='months', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('and_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_app.courses')),
                ('teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_app.teacherprofil')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Cancelled')], default='active', max_length=25)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.studentprofil')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.groups')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
