# Generated by Django 5.2.4 on 2025-09-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_courses_groups_enrollments_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='and_date',
            new_name='end_date',
        ),
    ]
