# Generated by Django 5.2.4 on 2025-09-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_rename_and_date_groups_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.courses'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.teacherprofil'),
        ),
    ]
