# Generated by Django 5.2.4 on 2025-09-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_alter_groups_course_id_alter_groups_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofil',
            old_name='birth_data',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='teacherprofil',
            old_name='exprence_years',
            new_name='experience_years',
        ),
        migrations.AddField(
            model_name='groups',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='Pending', max_length=25),
        ),
    ]
