# Generated by Django 5.2.4 on 2025-09-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
