# Generated by Django 5.2.4 on 2025-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0009_delete_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollments',
            constraint=models.UniqueConstraint(fields=('student_id', 'group_id'), name='unique_student_group'),
        ),
    ]
