# Generated by Django 5.2.4 on 2025-09-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0010_enrollments_unique_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
