# Generated by Django 5.2.4 on 2025-09-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0011_enrollments_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
